### ISSUE TITLE
using Eventjs in browser instead of Nodejs

### ISSUE THREAD

**Issue by brendonco** [kevinconway/Event.js#8]
Hi,
I'm trying to setup eventjs to include in browser, but was not able to configure successfully.

HTML:
<script src="./lib/require.js"></script>
<script src="./js/main.js"></script>

eventjs after build using grunt:
lib\event.browser.min.js

main.js:
var EventEmit = require(['./lib/event.browser.min']);
var EventEmitter = new EventEmit();

EventEmitter.emit('start'); //-->>> failed no emit function.

**Comment by kevinconway** [comment]
When you pass a list of dependencies to `require` you also need to pass in a callback that is executed once the modules are loaded. For example:

```javascript
require(['./lib/event.browser.min.js'], function (EventEmitter) {
    var emitter = new EventEmitter();
    emitter.emit('start');
})
```

Alternatively, it looks like requirejs also supports CommonJS style `require` if the first argument is a string. I'm not sure how that affects the normal, async behaviour, though.

```javascript
var EventEmitter = require('./lib/event.browser.min.js'),
    emitter = new EventEmitter();

emitter.emit('start');
```

If you drop requirejs and load the module with a `<script></script>` instead the module is loaded under the global name `eventjs`. The global name is configurable through the browserify section of the Gruntfile.js

```html
<script src='./lib/event.browser.min.js'></script>
<script>
var emitter = new eventjs();
emitter.emit('start');
</script>
```

**Comment by kevinconway** [comment]
Hey, I'm going to close this issue. Thanks for reaching out and let me know if you hit any other hurdles working with this module.

**Comment by brendonco** [comment]
sure you can close this Keviin thanks for the help.  I wrote my own event emitter since I only need a broadcast and receiver event. :) Thanks

**Comment by kevinconway** [comment]
My pleasure. One thing to keep in mind if you are writing your own emitter is how you will handle the async nature of events. My event emitter implementation uses another one of my libraries called [defer.js](https://github.com/kevinconway/defer.js). It handles choosing the best method for "do something later" depending on the platform.

Unless your browser supports `setImmediate` you will need to leverage `window.postMessage` to emulate some of the async deferral behaviour of node.js. I might recommend either using the `defer.js` module directly or adding support to your emitter for window.postMessage. This is an important factor in ensuring that your events emitted don't block when there are listeners registered.
