### ISSUE TITLE
emit() does not emit arguments properly

### ISSUE THREAD

**Issue by bcronin** [kevinconway/Event.js#9]
Calling emit with arguments always passes `undefined` as the first argument.

```js
  EventMixin.prototype.emit = function emit(event) {

    var listenerArgs = [],
      length = arguments.length,
      x,
      numberListeners,
      remove = [];

    // This loop is not right as it leaves listenerArgs[0] as undefined
    for (x = 1; x < length; x = x + 1) {
      listenerArgs[x] = arguments[x];
    }
```

The fix is trivial:

```js    
    for (x = 0; x < length - 1; x++) {
      listenerArgs[x] = arguments[x+1];
    }
```

Hope this helps.

**Comment by kevinconway** [comment]
@bcronin Thanks a bunch for reporting this bug. It looks like this was a mistake I made when converting to an interface that matches the EventEmitter spec. I've pushed up #10 to resolve the issue and added a test to prevent regression. I'll have the new patch version released to NPM shortly.

**Comment by kevinconway** [comment]
The new patch is up. Be sure to let me know if you hit any other bugs.
